# config.yaml
app:
  name: "trim"
  version: "0.2.0"

filesystem:
  rel_input_path: "../input"
  rel_output_path: "../output"
  lib_path: "../lib"
  conf_path: "../etc"
  model_path: "../lib/models"
  profile_test_path: "../lib/tests"
  db_path: "../lib/db"

filter:
  filter_list: 
    - "a"
    - "map_toint"

profile:
  profile_levels:
    - level: "l1"
      tests:
        - "event_uniqueness"
        - "time_dist"
        - "row_dup"
    - level: "l2"
      tests:
        - "flood_score"
  
# Note: Test-specific parameters are transferred to lib/tests/<test>/etc/t_config.yaml.

trimming:
  trim_strategy_list:
    - 'event'
    - 'block'
    - 'total'

model:
  model_list: 
    - "event_age"
    - "event_statistical"
    - "event_time_resolution"
    - "class_statistical"
    - "ideal_perception"

var:
  time_unit: "s"
  # trim generated index column
  index_column: "i_Dx"
  db_engine: "mysql"
  
